export const START_TIMER_1 = "START_TIMER_1";
export const START_TIMER_2 = "START_TIMER_2";
export const INCREMENT_TIMER_1 = "INCREMENT_TIMER_1";
export const INCREMENT_TIMER_2 = "INCREMENT_TIMER_2";
